---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mohammed/public_html/mwss/
    
    # Deploy files but exclude DB config
    - /bin/rsync -av \
        --exclude='application/config/database.php' \
        * $DEPLOYPATH/