---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mohammed/public_html/mwss
    - /bin/cp -R * $DEPLOYPATH/
    - /bin/rm -f $DEPLOYPATH/database.local.php
    - /bin/rm -f $DEPLOYPATH/.cpanel.yml
    - /bin/rm -rf $DEPLOYPATH/.git
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;