---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mohammed/public_html/mwss/
    
    # Deploy everything but keep database.php untouched
    - /bin/rsync -av --delete \
        --exclude='application/config/database.php' \
        ./ $DEPLOYPATH/