---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mohammed/public_html/mwss/
    # Create deployment directory if it doesn't exist
    - mkdir -p $DEPLOYPATH
    # Copy all files except the local database config file
    - rsync -av --exclude='database.local.php' --exclude='.git/' --exclude='node_modules/' --exclude='*.log' . $DEPLOYPATH
    # Set proper permissions
    - find $DEPLOYPATH -type f -exec chmod 644 {} \;
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;